import type { NextPage } from "next";
import Head from "next/head";

import * as React from "react";
import { Box, Typography, Hidden, Button, Grid } from "@mui/material";
import CssBaseline from "@mui/material/CssBaseline";

import { Theme } from "../components/theme";
import { DarkModeToggle } from "../components/dark-mode-toggle";
import { CompanyLogo } from "../components/company-logo";
import { ParticlesBlock } from "../components/particles-block";
import { Card } from "../components/card";
import { SectionHeader } from "../components/section-header";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const router = useRouter();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Theme>
          <CssBaseline />
          <ParticlesBlock>
            <div style={{ marginTop: "140px" }}>
              <Typography variant={"h2"} color={"primary"} gutterBottom>
                Next.js Template
              </Typography>
              <Hidden smDown>
                <Typography variant={"h3"} style={{ marginBottom: "32px" }}>
                  Progressive web
                </Typography>
              </Hidden>
              <CompanyLogo sx={{ height: "48px" }} />
            </div>
          </ParticlesBlock>
          <Box>
            <SectionHeader
              title="Features"
              description={`
              Sed mauris dui, porta cursus convallis eu, finibus sit amet mi. 
              Nulla pulvinar posuere massa, mattis feugiat nibh sodales vel. 
              Donec non malesuada magna. Nullam id augue accumsan, ornare lectus euismod, 
              egestas ipsum.`}
            />
            <Grid container sx={{ p: 2 }} spacing={2}>
              <Grid item xs={4}>
                <Card
                  title="History"
                  image={`/assets/background-0.png`}
                  description={`Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
                    Praesent venenatis feugiat rutrum. 
                    Ut placerat mi sollicitudin diam hendrerit interdum. 
                    Duis ultrices lectus eget erat facilisis ornare a ut ex.
                    Sed cursus hendrerit ligula, ut semper nibh cursus ornare. 
                    Duis interdum diam non nulla facilisis, et euismod lectus porttitor.`}
                  actions={
                    <>
                      <Button
                        size="small"
                        onClick={() => {
                          router.push("/history");
                        }}
                      >
                        Share
                      </Button>
                    </>
                  }
                />
              </Grid>
              <Grid item xs={4}>
                <Card
                  title="Duis interdum"
                  image={`/assets/background-1.png`}
                  description={`Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
                    Praesent venenatis feugiat rutrum. 
                    Ut placerat mi sollicitudin diam hendrerit interdum. 
                    Duis ultrices lectus eget erat facilisis ornare a ut ex.
                    Sed cursus hendrerit ligula, ut semper nibh cursus ornare. 
                    Duis interdum diam non nulla facilisis, et euismod lectus porttitor.`}
                  actions={
                    <>
                      <Button size="small">Share</Button>
                    </>
                  }
                />
              </Grid>
              <Grid item xs={4}>
                <Card
                  title="Praesent venenatis"
                  image={`/assets/background-2.png`}
                  description={`Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
                  Praesent venenatis feugiat rutrum. 
                  Ut placerat mi sollicitudin diam hendrerit interdum. 
                  Duis ultrices lectus eget erat facilisis ornare a ut ex.
                  Sed cursus hendrerit ligula, ut semper nibh cursus ornare. 
                  Duis interdum diam non nulla facilisis, et euismod lectus porttitor.`}
                  actions={
                    <>
                      <Button size="small">Share</Button>
                    </>
                  }
                />
              </Grid>
            </Grid>
          </Box>
          <div style={{ position: "absolute", top: 0, right: 0 }}>
            <DarkModeToggle />
          </div>
        </Theme>
      </main>
    </div>
  );
};

export default Home;
